version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Uncommented and specified Node.js version
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Pre-build phase - no specific commands for static site"
  build:
    commands:
      - echo "Starting build phase..."
      # Sync files from CodeBuild's workspace to S3 bucket
      # Replace www.ejiro.de with your S3 bucket name
      - aws s3 sync . s3://www.ejiro.de/ --delete --acl public-read
      - echo "Files synced to S3 bucket: s3://www.ejiro.de/"
  post_build:
    commands:
      - echo "Starting post-build phase - invalidating CloudFront cache..."
      # Invalidate CloudFront cache
      # Replace YOUR_CLOUDFRONT_DISTRIBUTION_ID with your actual CloudFront Distribution ID
      # You can find this ID in the CloudFront console (e.g., E123ABCDEFG)
      - aws cloudfront create-invalidation --distribution-id E1W81S3NGMZMEX --paths "/*"
      - echo "CloudFront cache invalidation initiated."

artifacts:
  # This section is not strictly needed for static site deployment to S3
  # but can be used if you want to store build output elsewhere.
  files:
    - '**/*'
  base-directory: .
